inherit_from: .rubocop_todo.yml

#AllCops:
#  Include:
#    - '**/Rakefile'
#    - '**/config.ru'
#  Exclude:
#    - 'test/fixtures/**/*'
#    - 'db/**/*'
#    - 'config/**/*'
#    - 'vendor/**/*'
#    - '/app/helpers/application_helper.rb'
